name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Runs a single command using the runners shell
      - name: Build React App
        run: yarn install && yarn build

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
